/**
 * Demo Home Assistant state store.
 * Simulates HA API responses. Real integration replaces this with HA REST/WebSocket.
 */

import type { HAStateStore } from "./types";
import { ENTITY_IDS } from "./entities";

const ts = () => new Date().toISOString();

export const initialHAState: HAStateStore = {
  [ENTITY_IDS.light_living_room_ceiling]: {
    entity_id: ENTITY_IDS.light_living_room_ceiling,
    state: "on",
    attributes: { brightness: 80, friendly_name: "Living Room Ceiling" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.light_living_room_led_strip]: {
    entity_id: ENTITY_IDS.light_living_room_led_strip,
    state: "on",
    attributes: {
      brightness: 60,
      rgb_color: [255, 107, 157],
      friendly_name: "Living Room LED Strip",
    },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.light_bedroom_bedside]: {
    entity_id: ENTITY_IDS.light_bedroom_bedside,
    state: "off",
    attributes: { brightness: 50, friendly_name: "Bedside Lamp" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.light_outdoor_porch]: {
    entity_id: ENTITY_IDS.light_outdoor_porch,
    state: "on",
    attributes: { brightness: 100, friendly_name: "Porch Light" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.light_garden]: {
    entity_id: ENTITY_IDS.light_garden,
    state: "off",
    attributes: { brightness: 70, friendly_name: "Garden Light" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.switch_study_plug]: {
    entity_id: ENTITY_IDS.switch_study_plug,
    state: "on",
    attributes: { power: 45, friendly_name: "Study Plug" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.switch_garage_strip_1]: {
    entity_id: ENTITY_IDS.switch_garage_strip_1,
    state: "on",
    attributes: { friendly_name: "Garage Strip 1" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.switch_garage_strip_2]: {
    entity_id: ENTITY_IDS.switch_garage_strip_2,
    state: "off",
    attributes: { friendly_name: "Garage Strip 2" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.switch_garage_strip_3]: {
    entity_id: ENTITY_IDS.switch_garage_strip_3,
    state: "on",
    attributes: { friendly_name: "Garage Strip 3" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.switch_kitchen_microwave]: {
    entity_id: ENTITY_IDS.switch_kitchen_microwave,
    state: "off",
    attributes: { friendly_name: "Microwave" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.switch_kitchen_coffee]: {
    entity_id: ENTITY_IDS.switch_kitchen_coffee,
    state: "off",
    attributes: { strength: "medium", friendly_name: "Coffee Machine" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.switch_outdoor_sprinkler]: {
    entity_id: ENTITY_IDS.switch_outdoor_sprinkler,
    state: "off",
    attributes: { schedule: "06:00,18:00", friendly_name: "Sprinkler" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.switch_outdoor_lights]: {
    entity_id: ENTITY_IDS.switch_outdoor_lights,
    state: "off",
    attributes: { brightness: 80, friendly_name: "Outdoor Lights" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.switch_virtual_test]: {
    entity_id: ENTITY_IDS.switch_virtual_test,
    state: "off",
    attributes: { friendly_name: "Virtual Test Switch" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.sensor_bathroom_humidity]: {
    entity_id: ENTITY_IDS.sensor_bathroom_humidity,
    state: "45",
    attributes: { unit_of_measurement: "%", friendly_name: "Bathroom Humidity" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.sensor_living_room_temperature]: {
    entity_id: ENTITY_IDS.sensor_living_room_temperature,
    state: "21",
    attributes: { unit_of_measurement: "°C", friendly_name: "Living Room Temperature" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.sensor_study_power]: {
    entity_id: ENTITY_IDS.sensor_study_power,
    state: "45",
    attributes: { unit_of_measurement: "W", friendly_name: "Study Plug Power" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.sensor_energy_meter]: {
    entity_id: ENTITY_IDS.sensor_energy_meter,
    state: "12.4",
    attributes: { unit_of_measurement: "kWh", friendly_name: "Energy Meter" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.sensor_bluetooth_presence]: {
    entity_id: ENTITY_IDS.sensor_bluetooth_presence,
    state: "home",
    attributes: { friendly_name: "Phone Presence" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.binary_sensor_door_main]: {
    entity_id: ENTITY_IDS.binary_sensor_door_main,
    state: "off",
    attributes: { friendly_name: "Front Door" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.binary_sensor_window_living]: {
    entity_id: ENTITY_IDS.binary_sensor_window_living,
    state: "off",
    attributes: { friendly_name: "Living Room Window" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.binary_sensor_motion_living]: {
    entity_id: ENTITY_IDS.binary_sensor_motion_living,
    state: "off",
    attributes: { friendly_name: "Living Room Motion" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.binary_sensor_smoke_kitchen]: {
    entity_id: ENTITY_IDS.binary_sensor_smoke_kitchen,
    state: "off",
    attributes: { friendly_name: "Smoke Detector" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.binary_sensor_gas_kitchen]: {
    entity_id: ENTITY_IDS.binary_sensor_gas_kitchen,
    state: "off",
    attributes: { level: 0, friendly_name: "Gas Sensor" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.binary_sensor_water_leak_bathroom]: {
    entity_id: ENTITY_IDS.binary_sensor_water_leak_bathroom,
    state: "off",
    attributes: { friendly_name: "Water Leak Bathroom" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.binary_sensor_fridge_door]: {
    entity_id: ENTITY_IDS.binary_sensor_fridge_door,
    state: "off",
    attributes: { friendly_name: "Fridge Door" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.lock_front_door]: {
    entity_id: ENTITY_IDS.lock_front_door,
    state: "locked",
    attributes: { friendly_name: "Front Door Lock" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.climate_living_room_ac]: {
    entity_id: ENTITY_IDS.climate_living_room_ac,
    state: "cool",
    attributes: {
      temperature: 22,
      hvac_mode: "cool",
      fan_mode: "medium",
      friendly_name: "Living Room AC",
    },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.climate_bathroom_heater]: {
    entity_id: ENTITY_IDS.climate_bathroom_heater,
    state: "off",
    attributes: { temperature: 24, friendly_name: "Bathroom Heater" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.cover_living_room_curtains]: {
    entity_id: ENTITY_IDS.cover_living_room_curtains,
    state: "open",
    attributes: { current_position: 75, friendly_name: "Living Room Curtains" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.cover_study_blinds]: {
    entity_id: ENTITY_IDS.cover_study_blinds,
    state: "open",
    attributes: { current_position: 50, friendly_name: "Study Blinds" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.fan_bedroom]: {
    entity_id: ENTITY_IDS.fan_bedroom,
    state: "on",
    attributes: { percentage: 66, friendly_name: "Bedroom Fan" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.alarm_control_panel_home]: {
    entity_id: ENTITY_IDS.alarm_control_panel_home,
    state: "disarmed",
    attributes: { friendly_name: "Home Alarm" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.camera_indoor_living]: {
    entity_id: ENTITY_IDS.camera_indoor_living,
    state: "idle",
    attributes: { friendly_name: "Indoor Camera" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.camera_outdoor_front]: {
    entity_id: ENTITY_IDS.camera_outdoor_front,
    state: "idle",
    attributes: { friendly_name: "Outdoor Camera" },
    last_changed: ts(),
    last_updated: ts(),
  },
  [ENTITY_IDS.cover_gate_driveway]: {
    entity_id: ENTITY_IDS.cover_gate_driveway,
    state: "closed",
    attributes: { friendly_name: "Gate" },
    last_changed: ts(),
    last_updated: ts(),
  },
};
